package business;

import java.io.IOException;

import domain.Utils;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.scene.input.MouseEvent;

public class GUIMainWindowController {
	@FXML
	private AnchorPane apMain;
	@FXML
	private Label lblTicoTech;
	@FXML
	private Label lblView;
	@FXML
	private Label lblFavorite;
	@FXML
	private Label lblCart;
	@FXML
	private Label lblcatalog;
	
	@FXML
	private Label lblComment;


	@FXML
	public void openCatalog(MouseEvent event) {
	    System.out.println("Abriendo catálogo...");

	    try {
	        FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIMarket.fxml"));
	        Parent root = loader.load();

	        // Obtiene el controlador después de cargar la vista
	        GUIMarketController controller = loader.getController();
	        
	       

	        Scene scene = new Scene(root);
	        Stage stage = new Stage();
	        stage.setScene(scene);
	        scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
	        stage.show();

	   
	        stage.setOnCloseRequest(e -> controller.closeWindows());

	        // Cierra la ventana actual
	        Stage temp = (Stage) this.lblcatalog.getScene().getWindow();
	        temp.close();

	    } catch (Exception e) {
	        e.printStackTrace();
	    }
	}

	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void openCart(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("Carro");
	//	clientF.openCart();
		 try {
	            FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUICart.fxml"));
	            Parent root = loader.load();

	            Scene scene = new Scene(root);
	            Stage stage = new Stage();
	            stage.setScene(scene);
	            scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
	            stage.show();

	            GUICartController controller = loader.getController();
	            
	            
	            stage.setOnCloseRequest(e -> controller.closeWindows());

	            Stage temp = (Stage) this.lblcatalog.getScene().getWindow();
	            temp.close();
	        } catch (Exception e) {
	            e.printStackTrace();
	        }
		
	}
	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void openFavorites(MouseEvent event) {
		
	    try {
	     
	        FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIFav.fxml"));
	        Parent root = loader.load();

	        GUIFavController favController = loader.getController();
	      

	        Stage stage = new Stage();
	        stage.setScene(new Scene(root));
	        stage.setTitle("Productos Favoritos");
	        stage.show();
	        
	        stage.setOnCloseRequest(e -> favController.closeWindows());
	        
	        Stage temp = (Stage) this.lblcatalog.getScene().getWindow();
	        temp.close();
	    } catch (IOException e) {
	        e.printStackTrace();
	    }
	}
	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void viewProfile(MouseEvent event) {
		System.out.println("Perfil");
		 try {
	            FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIViewProfile.fxml"));
	            Parent root = loader.load();

	            Scene scene = new Scene(root);
	            Stage stage = new Stage();
	            stage.setScene(scene);
	            scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
	            stage.show();

	            GUIViewProfileController controller = loader.getController();
	  
	            
	            stage.setOnCloseRequest(e -> controller.closeWindows());

	            Stage temp = (Stage) this.lblcatalog.getScene().getWindow();
	            temp.close();
	        } catch (Exception e) {
	            e.printStackTrace();
	        }
		
		
	}
	
	public void closeWindows() {
		 try {
	            FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUILogin.fxml"));
	            Parent root = loader.load();

	            Scene scene = new Scene(root);
	            Stage stage = new Stage();
	            stage.setScene(scene);
	            scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
	            stage.show();

	            GUILoginController controller = loader.getController();
	       

	            Stage temp = (Stage) this.lblcatalog.getScene().getWindow();
	            temp.close();
	        } catch (Exception e) {
	            e.printStackTrace();
	        }
		
	}
	@FXML
	public void openComment(MouseEvent event) {
		 try {
	            FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIComment.fxml"));
	            Parent root = loader.load();

	            Scene scene = new Scene(root);
	            Stage stage = new Stage();
	            stage.setScene(scene);
	            scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
	            stage.show();

	            GUICommentController controller = loader.getController();
	      //      controller.loadData(clientF);
	            
	            stage.setOnCloseRequest(e -> controller.closeWindows());

	            Stage temp = (Stage) this.lblcatalog.getScene().getWindow();
	            temp.close();
	        } catch (Exception e) {
	            e.printStackTrace();
	        }
		
	}
}
